# Generated by Django 4.1.6 on 2023-02-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parquet', '0003_alter_parquetwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parquetwork',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
